[package]
name = "pg_async"
version = "0.1.0"
authors = ["Artem <artemciy@gmail.com>"]
links = "pq"
build = "build.rs"

[lib]
name = "pg_async"
path = "src/lib.rs"
crate-type = ["rlib"]
doctest = false 

[dependencies]
gstuff = "0.1"
lazy_static = "0.2"
libc = "0.2"
nix = "0.7"

[build-dependencies]
