[package]
name = "pg_async"
version = "0.2.1"
authors = ["Artem <artemciy@gmail.com>"]
links = "pq"
build = "build.rs"
description = "Asynchronous, HA (master-master) PostgreSQL driver on top of libpq"
#documentation = "..."
repository = "https://github.com/ArtemGr/pg_async.rs"
keywords = ["futures", "high availability"]
license = "MIT"

[lib]
name = "pg_async"
path = "src/lib.rs"
crate-type = ["rlib"]
doctest = false 

[dependencies]
futures = "0.1"
gstuff = "0.1"
itertools = "0.5"
lazy_static = "0.2"
libc = "0.2"
nix = "0.7"
serde_json = "0.8"

[build-dependencies]
